### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-tanialopezab#1]
Good job @tanialopezab  !!!

Here you have some tips to finish the exercise:

- [x] Fix the language and the meta title of the page
- [x] Be **extra careful with syntax, content should be inside `body` tag**
- [x] Before adding extra divs and classes focus on your HTML semantic, `main` tag shouldn't be inside the header, menu items and logo should be clickable.
- [x] Download the Adalab logo to a proper folder (although it is ok to use an absolute path we are going to use relative paths to a project file)
- [x] Humanize text in `alt` attributes, a sentence without the hyphen may do the trick.
- [x] Move the font CSS before your main CSS
- [x] Class selectors are free, let's use them instead tag selectors 
- [x] Improve hierarchy adding more common styles to `body` tag as font-size, font-family, font-weight, color, background-color
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https://books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with the main content.
And finally, add the tablet styles.

Let me know if you have any doubts.

Do not panic and go for it ;)

**Comment by tanialopezab** [comment]
I think all the issues are ok. The web page is better than the first version but I  
I have watched the video shared by Carlos this morning, and de documents on gitHub  and I would like to make some changes and improvements on Monday

**Comment by tanialopezab** [comment]
I'ḿ so sorry I made a comment but I did not add you. @nasivuela

**Comment by nasivuela** [comment]
@tanialopezab The `HTML` has syntax errors, actually, it doesn't work on Github Pages. Review it carefully to fix it ;)

**Comment by tanialopezab** [comment]
The problem with the links between the css and the html is solved.
I see the page correctly on Github pages. Thank you so much @nasivuela

**Comment by nasivuela** [comment]
@tanialopezab I have unchecked a few points that still need some work:

- The meta title of the page shouldn't be about you or de evaluation. Something like 'Adalab Digital' may do the trick.
- Be careful with syntax on HTML you have an extra `"` on `img` tag, Chrome fixes it but in other browsers, it can break the page. You can see clearly how the tag colors change on Github --> https://github.com/Adalab/f-m1-evaluacion-intermedia-tanialopezab/blob/master/index.html
- Indentation can be improved!

And here you have some other things to improve:

- [ ] Fix text colors of menu links
- [ ] Fix font size of the main title
- [ ] Fix font weight of the main title


Go!

**Comment by tanialopezab** [comment]
Thank you for the corrections @nasivuela ! I'm learning a lot ;-) I have made more improvements and a lot of commits, sorry.

**Comment by nasivuela** [comment]
@tanialopezab You got it!!! Only the weight of the title is pending, to make it work you need to add that version of 'Rubik' on the link of the head. Go to google fonts page to find the correct link ;)

It's a little detail I'll leave to you. I'm closing this because I consider it done ;)

![](https://media.giphy.com/media/AGOPaltgJ2pBC/giphy.gif)
